AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LivewellCoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: livewell-core-layer
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
        - python3.11
      RetentionPolicy: Delete

Outputs:
  LayerVersionArn:
    Description: ARN of the livewell-core layer
    Value: !Ref LivewellCoreLayer
    Export:
      Name: !Sub ${AWS::StackName}-layer-arn